import { Provider, Car } from './types'

export const providers: Provider[] = [
  {
    id: '4hire',
    name: '4 HIRE',
    tagline: 'No Deposit Deals',
    badge: '🔑',
    promoTitle: '4 HIRE Special Offers',
    promoText: 'No-deposit rentals on selected sports cars and SUVs. Fast WhatsApp booking, same-day delivery available across Dubai.',
    featured: true,
    color: 'amber',
  },
  {
    id: 'habibcar',
    name: 'HABIB CAR',
    tagline: 'Best Daily Prices',
    badge: '💰',
    promoTitle: 'HABIB CAR Daily Deals',
    promoText: 'Dubai\'s most affordable daily rental rates. Economy to mid-range fleet, fully insured, with flexible pickup locations.',
    featured: true,
    color: 'emerald',
  },
  {
    id: 'exoticcar',
    name: 'EXOTIC CAR',
    tagline: 'Luxury Fleet',
    badge: '💎',
    promoTitle: 'EXOTIC CAR Collection',
    promoText: 'Lamborghini, Ferrari, Mercedes AMG and more. Exclusive weekly packages and VIP concierge delivery to your door.',
    featured: true,
    color: 'violet',
  },
  {
    id: 'royaldrive',
    name: 'ROYAL DRIVE',
    tagline: 'Sports & SUV',
    badge: '🏎️',
    promoTitle: 'ROYAL DRIVE Exclusives',
    promoText: 'Performance sports cars and premium SUVs. Special weekend rates and monthly packages for long-term renters.',
    featured: false,
    color: 'blue',
  },
  {
    id: 'elitedrive',
    name: 'ELITE DRIVE',
    tagline: 'Premium Collection',
    badge: '⭐',
    promoTitle: 'ELITE DRIVE Premium',
    promoText: 'Curated premium fleet for business and leisure. Full insurance, 24/7 roadside assistance, and door-to-door service.',
    featured: false,
    color: 'rose',
  },
]

export const cars: Car[] = [
  {
    id: 'mustang-2024',
    providerId: '4hire',
    providerName: '4 HIRE',
    brand: 'Ford',
    model: 'Mustang GT',
    year: 2024,
    category: 'Sports',
    dailyPrice: 350,
    weeklyPrice: 2100,
    monthlyPrice: 7500,
    depositType: 'no-deposit',
    availableNow: true,
    transmission: 'Automatic',
    seats: 4,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80',
    isHotDeal: true,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'The iconic American muscle car in its latest form. V8 power, Fastback styling, and zero deposit required.',
    features: ['V8 5.0L Engine', 'Fastback Body', 'Apple CarPlay', 'Rear Camera', 'Keyless Entry', 'Premium Audio'],
  },
  {
    id: 'mustang-2023',
    providerId: 'habibcar',
    providerName: 'HABIB CAR',
    brand: 'Ford',
    model: 'Mustang EcoBoost',
    year: 2023,
    category: 'Sports',
    dailyPrice: 280,
    weeklyPrice: 1680,
    monthlyPrice: 5900,
    depositType: 'no-deposit',
    availableNow: true,
    transmission: 'Automatic',
    seats: 4,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'Sporty performance at an accessible daily rate. EcoBoost turbocharged engine with full modern tech.',
    features: ['EcoBoost 2.3L Turbo', 'Sport Mode', 'Apple CarPlay', 'Android Auto', 'Rear Camera', 'Lane Assist'],
  },
  {
    id: 'camaro-2024',
    providerId: '4hire',
    providerName: '4 HIRE',
    brand: 'Chevrolet',
    model: 'Camaro SS',
    year: 2024,
    category: 'Sports',
    dailyPrice: 380,
    weeklyPrice: 2280,
    monthlyPrice: 8200,
    depositType: 'no-deposit',
    availableNow: true,
    transmission: 'Automatic',
    seats: 4,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: false,
    isNewArrival: true,
    shortDescription: 'Bold muscle with SS performance package. Wide body, V8 rumble, and a commanding presence on Dubai roads.',
    features: ['V8 6.2L Engine', 'SS Performance Pack', 'Brembo Brakes', 'Head-Up Display', 'Wireless CarPlay', 'Sport Exhaust'],
  },
  {
    id: 'camaro-2023',
    providerId: 'royaldrive',
    providerName: 'ROYAL DRIVE',
    brand: 'Chevrolet',
    model: 'Camaro LT1',
    year: 2023,
    category: 'Sports',
    dailyPrice: 320,
    weeklyPrice: 1920,
    monthlyPrice: 6800,
    depositType: 'deposit',
    depositAmount: 1500,
    availableNow: true,
    transmission: 'Automatic',
    seats: 4,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    isHotDeal: true,
    isPopular: false,
    isNewArrival: false,
    shortDescription: 'Track-ready performance for the road. Aggressive styling with the LT1 V8 making every drive extraordinary.',
    features: ['V8 LT1 Engine', 'Magnetic Ride Control', 'Launch Control', 'Dual-Zone AC', 'Leather Seats', 'Bose Audio'],
  },
  {
    id: 'patrol-2023',
    providerId: 'royaldrive',
    providerName: 'ROYAL DRIVE',
    brand: 'Nissan',
    model: 'Patrol Platinum',
    year: 2023,
    category: 'SUV',
    dailyPrice: 450,
    weeklyPrice: 2700,
    monthlyPrice: 9500,
    depositType: 'deposit',
    depositAmount: 2000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 8,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'The ultimate Dubai SUV. 8-seat platinum trim with V8 power, perfect for family trips or group travel across the UAE.',
    features: ['V8 5.6L Engine', '8-Seater', 'Platinum Interior', '4WD System', 'Triple Zone AC', 'Captain Seats', 'Sunroof'],
  },
  {
    id: 'g63-2023',
    providerId: 'exoticcar',
    providerName: 'EXOTIC CAR',
    brand: 'Mercedes-Benz',
    model: 'G 63 AMG',
    year: 2023,
    category: 'Luxury',
    dailyPrice: 1200,
    weeklyPrice: 7200,
    monthlyPrice: 24000,
    depositType: 'deposit',
    depositAmount: 5000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1563720223809-b2d1abf4e3ad?auto=format&fit=crop&w=800&q=80',
    isHotDeal: true,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'The legendary G-Wagon AMG. 585hp Biturbo V8, iconic box-body design, supreme off-road capability, and unmatched street presence.',
    features: ['AMG V8 Biturbo 585hp', 'Designo Interior', 'Burmester Sound', 'AMG Ride Control', 'Night Package', 'Panoramic Roof', 'Heated Seats'],
  },
  {
    id: 'urus-2024',
    providerId: 'exoticcar',
    providerName: 'EXOTIC CAR',
    brand: 'Lamborghini',
    model: 'Urus S',
    year: 2024,
    category: 'Exotic',
    dailyPrice: 2500,
    weeklyPrice: 15000,
    monthlyPrice: 50000,
    depositType: 'deposit',
    depositAmount: 10000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: true,
    isNewArrival: true,
    shortDescription: 'The world\'s most exciting SUV. 666hp twin-turbo V8, Lamborghini DNA in a practical form, for those who demand the extraordinary.',
    features: ['V8 Twin-Turbo 666hp', 'ANIMA Drive Modes', 'Carbon Ceramic Brakes', '23" Forged Wheels', 'Alcantara Interior', 'B&O Sound'],
  },
  {
    id: 'bmw7-2024',
    providerId: 'elitedrive',
    providerName: 'ELITE DRIVE',
    brand: 'BMW',
    model: '7 Series 760i',
    year: 2024,
    category: 'Luxury',
    dailyPrice: 700,
    weeklyPrice: 4200,
    monthlyPrice: 15000,
    depositType: 'deposit',
    depositAmount: 3000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: false,
    isNewArrival: true,
    shortDescription: 'BMW\'s flagship redefined. Theatre Screen, Executive Lounge seating, and V12 performance for the ultimate business class experience.',
    features: ['V12 Engine', 'Theatre Screen', 'Executive Lounge', 'Crystal Headlights', 'Massage Seats', 'Bowers & Wilkins Audio', 'Rear Entertainment'],
  },
  {
    id: 'rrsport-2024',
    providerId: 'elitedrive',
    providerName: 'ELITE DRIVE',
    brand: 'Range Rover',
    model: 'Sport HSE',
    year: 2024,
    category: 'SUV',
    dailyPrice: 900,
    weeklyPrice: 5400,
    monthlyPrice: 19000,
    depositType: 'deposit',
    depositAmount: 4000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1616788494707-ec28f08d05a1?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: false,
    isNewArrival: true,
    shortDescription: 'Effortless sophistication in an SUV. New curved dashboard, Digital Air Suspension, and impeccable British refinement.',
    features: ['3.0L Inline-6 Turbo', 'Digital Air Suspension', 'Meridian Sound', 'Curved Dash Display', 'Heated & Cooled Seats', 'Terrain Response 2'],
  },
  {
    id: 'landcruiser-2023',
    providerId: 'habibcar',
    providerName: 'HABIB CAR',
    brand: 'Toyota',
    model: 'Land Cruiser VX',
    year: 2023,
    category: 'SUV',
    dailyPrice: 400,
    weeklyPrice: 2400,
    monthlyPrice: 8500,
    depositType: 'no-deposit',
    availableNow: true,
    transmission: 'Automatic',
    seats: 7,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'The undisputed king of UAE roads. 7-seater VX trim, no-deposit offer, with legendary reliability and commanding off-road performance.',
    features: ['V6 3.5L Twin-Turbo', '7-Seater', 'Multi-Terrain Select', 'E-KDSS Suspension', 'JBL Premium Audio', 'Triple Zone AC'],
  },
  {
    id: 'cayenne-2024',
    providerId: 'royaldrive',
    providerName: 'ROYAL DRIVE',
    brand: 'Porsche',
    model: 'Cayenne S',
    year: 2024,
    category: 'SUV',
    dailyPrice: 850,
    weeklyPrice: 5100,
    monthlyPrice: 18000,
    depositType: 'deposit',
    depositAmount: 3500,
    availableNow: false,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: false,
    isNewArrival: true,
    shortDescription: 'Sports car performance in SUV clothing. The Cayenne S delivers a driving experience no other SUV can match.',
    features: ['V6 2.9L Biturbo', 'PASM Sport Suspension', 'Air Suspension', 'Bose Surround', 'Sport Chrono Package', '21" Turbo Wheels'],
  },
  {
    id: 'ferrari-roma-2024',
    providerId: 'exoticcar',
    providerName: 'EXOTIC CAR',
    brand: 'Ferrari',
    model: 'Roma',
    year: 2024,
    category: 'Exotic',
    dailyPrice: 3500,
    weeklyPrice: 21000,
    monthlyPrice: 70000,
    depositType: 'deposit',
    depositAmount: 15000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 2,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1544544784-f748eed3a2e4?auto=format&fit=crop&w=800&q=80',
    isHotDeal: true,
    isPopular: false,
    isNewArrival: false,
    shortDescription: 'La Dolce Vita redefined. The Ferrari Roma is a tour de force of Italian design and V8 performance — the ultimate Dubai statement.',
    features: ['V8 620hp', 'Maranello DNA', 'Roma Cockpit', 'Ferrari Dynamic Enhancer', 'Carbon Fibre Pack', 'Racing Seats'],
  },
]

export const getCarById = (id: string): Car | undefined =>
  cars.find((car) => car.id === id)

export const getCarsByProvider = (providerId: string): Car[] =>
  cars.filter((car) => car.providerId === providerId)

export const getHotDeals = (): Car[] =>
  cars.filter((car) => car.isHotDeal)

export const getPopularCars = (): Car[] =>
  cars.filter((car) => car.isPopular)

export const getNewArrivals = (): Car[] =>
  cars.filter((car) => car.isNewArrival)

export const getProviderById = (id: string): Provider | undefined =>
  providers.find((p) => p.id === id)
